### ISSUE TITLE
Directory traversal is not allowed in source path

### ISSUE THREAD

**Issue by nathanle** [rosell-dk/webp-convert#203]
I keep getting this error:

"Conversion failed!Directory traversal is not allowed in source path"

Output from test:
Converter set to: wpc

*WebP Convert 2.1.4*  ignited.
- PHP version: 5.6.30
- Server software: Apache

Wpc converter ignited

Options:
------------
The following options have been set explicitly. Note: it is the resulting options after merging down the "jpeg" and "png" options and any converter-prefixed options.
- source: /home/content/a2pewpnaspod04_data06/43/41702543/html/wp-content/plugins/webp-express/test/test-pattern-tv.jpg
- destination: /home/content/a2pewpnaspod04_data06/43/41702543/html/wp-content/webp-express/webp-images/doc-root/wp-content/plugins/webp-express/test/test-pattern-tv.jpg.webp
- default-quality: 70
- encoding: "auto"
- log-call-arguments: true
- max-quality: 80
- metadata: "none"
- near-lossless: 60
- quality: "auto"
- api-key: *****
- api-url: *****
- api-version: 1
- crypt-api-key-in-transfer: false

The following options have not been explicitly set, so using the following defaults:
- alpha-quality: 85
- auto-filter: false
- low-memory: false
- method: 6
- preset: "none"
- size-in-percentage: null (not set)
- skip: false
- use-nice: false
- secret: ""
- url: ""
------------

Quality set to same as source: 0
Bummer, we did not receive an image
What we received starts with: "Conversion failed!Directory traversal is not allowed in source path..."

I have Indexes removed from the Apache path options. I am using this with webp-convert-cloud-service. Any ideas?

Thanks!

**Comment by nathanle** [comment]
I also get the same error using curl locally.

**Comment by rjgra** [comment]
I also get the same error using  php 7.3

"Conversion failed!Directory traversal is not allowed in source path"

**Comment by rosell-dk** [comment]
Sorry for the late answer! Stuff had been piling up on my desk. Was just about to write an answer months ago but got pulled away and forgot about it.

Directory traversal is paths that contains double dots ("../"). I introduced denying such paths for security reasons. I was thinking that directory traversal would be suspect was going on. Well, it could be. A path such as '/var/www/website/../../etc/apache2/sites-available/website.com.conf' is probably due to somebody trying to do something bad. But I have just decided that it is not the responsibility of this library to prevent directory traversal. There could be perfectly valid reasons that a path has directory traversal in it. And sanitizing should generally be done sooner rather than later. So I will remove that check in the next release, which will be in a few days. I will however keep the checks that prevents control characters and stream wrappers as I see no use case for these, except evil.

Btw, the directory traversal you have is probably because you used the script in the README on webp-convert-cloud-service:

```
$options = [
    // Set dir for storing converted images temporarily
    // (make sure to create that dir, with permissions for web server to write)
    'destination-dir' => '../conversions',
   ...
```

If you change '../conversions' to `dirname(__DIR__) . '/conversions`, you should have a path that does not contain directory traversal.
