### ISSUE TITLE
WebP not rendering as webp format

### ISSUE THREAD

**Issue by mofizul21** [rosell-dk/webp-convert#270]
Hi, 

Thanks a lot for creating the plugin. I have an issue. 

I've used this code `<?php echo get_the_post_thumbnail(); ?>` in my post loop for displaying image. I see webp images are creating in the folder, but not rendering. It's rendering as jpg format, but I want to render as webp. If you inspect <a href="http://prntscr.com/11lyspl" rel="noopener" target="_blank">here the screenshot</a> on the website, you can see it. 

Why it's happening? Or how I can solve it?

Regards,

**Comment by rosell-dk** [comment]
Hi,

Sorry for not replying earlier.
Actually, your question is regarding WebP Express, and should have been posted in that [issue queue](https://github.com/rosell-dk/webp-express/issues).

The HTML is not necessarily altered - only if you enable the Alter HTML option. Otherwise, apache rewrite rules makes sure to redirect the image request for the jpeg to the converted webp.
