### ISSUE TITLE
Conversion with cwebp takes much longer with version 2.3.0+

### ISSUE THREAD

**Issue by mrbig00** [rosell-dk/webp-convert#285]
Simply downgrading the package to 2.2.2 resolves the issue. Tested on multiple php versions and multiple servers

**Comment by rosell-dk** [comment]
Did you test by calling the binary directly or through this library (master branch)?

**Comment by rosell-dk** [comment]
I'm asking because if you have tested through this library, it might be due to the new sharp_yuv option. It is *ON* per default (in master, and planned to be in 2.6.0 too). https://github.com/rosell-dk/webp-convert/issues/267

**Comment by rosell-dk** [comment]
Hm. Which converter is doing the conversion?

**Comment by rosell-dk** [comment]
Looking at the [2.3.0 milestone](https://github.com/rosell-dk/webp-convert/milestone/17?closed=1), I can see that most changes are related to the cwebp converter. So I'm guessing that your active converter is cwebp? 

It might be [this feature](https://github.com/rosell-dk/webp-convert/issues/226) that is costly. It tries executing "which -a cwebp" and "whereis -b cwebp" in order to locate path for cwebp. Can you try to disable the feature and see if that helps? You disable the feature by setting the *try-discovering-cwebp* option to *false*

**Comment by rosell-dk** [comment]
You can try to disable all the methods of discovering callable cwebps in the system by setting the following options to *false*:
*cwebp-try-cwebp* *cwebp-try-common-system-paths* *cwebp-try-discovering-cwebp* *cwebp-try-supplied-binary-for-os*

You probably need at least one of them to be on, though!
Look at the conversion log before turning the methods off in order to find out which of them you need to be on

**Comment by mrbig00** [comment]
I'm using ```cwebp-try-supplied-binary-for-os```  ```true``` and the others false

**Comment by rosell-dk** [comment]
I have added logging of time consumption in the sub processes in Cwebp. 
By examining the output, we can see which sub process that takes the time.

Here is an example of how you can see the log produced on conversion:
https://github.com/rosell-dk/webp-convert/blob/master/docs/v2.0/converting/introduction-for-converting.md#insights-to-the-process

**Comment by rosell-dk** [comment]
@mrbig00: Can you test it with the new time logging and paste the output here? Thanks

**Comment by rosell-dk** [comment]
The total time is the time used doing the actual conversion plus the overhead.

The time for the actual conversion varies depending on options and the image, and we cannot do anything about that. For very small images, it is as low as 10 ms on my machine. For 1MB images, it is around 200 ms.

The overhead consists of detecting available binaries, detecting their versions, ordering them in order to pick the highest version available and creating options. It is pretty constant around 70 ms on my machine when only `cwebp-try-supplied-binary-for-os` is enabled and around 85 ms when all methods for detecting cwebp binaries are enabled.

There are 4 supplied binaries for linux. If I comment out 3 of them, the overhead is decreased to 25 ms. Now, why does it take so long time detect a supplied binary? It turns out that it is the hash check that is expensive. It takes between 10-20 ms to create the checksum for each binary file.

Now, why not just have 1 supplied binary? The reason is that they have different dependencies. Some builds works on some systems, while others works on others. See #196 and #278.

But actually, some improvement could be made. There is no need to detect the versions of the supplied binaries, as we know what they are supposed to be beforehand. So the hash check could be postponed till right before doing the conversion. In case a cwebp binary is found using one of the other methods, and it is not an older version than the supplied binaries, no hash check will need to be run at all.

Until such optimizations are made, you could try disabling the "cwebp-try-supplied-binary-for-os" option and see if it still works. If it does, you should experience a significant performance gain.

**Comment by rosell-dk** [comment]
Hash-check is now postponed as described. Usually, only one hash-check will be needed now. However, if the newest binary doesn't work, an extra hash-check will be needed for the next-newest binary. It is probably pretty common that *cwebp-120-linux-x86-64* doesn't work, due to its dependencies (see #278). So on many systems, two hash-checks will be needed

**Comment by rosell-dk** [comment]
I could add an option to ignore a supplied binary that is known not to work

**Comment by rosell-dk** [comment]
Added option to skip supplied binaries that are known not to work on current system. It is documented [here](https://github.com/rosell-dk/webp-convert/blob/master/docs/v2.0/converting/options.md#cwebp-skip-these-precompiled-binaries)

**Comment by rosell-dk** [comment]
With these two changes, conversion with 2.6.0+ should be faster than 2.2.2

**Comment by rosell-dk** [comment]
Oh, btw: By setting an environment variable called "WEBPCONVERT_CWEBP_PATH", the discovering binaries step will be completely skipped, and there will be no hash-checking. Doing so however makes your system a little bit less secure - exactly because it bypasses the hash-checking. If some security whole allows an attacker to upload a binary, replacing the one set like this, an attacker would then have a way to have that binary executed. Apart from setting it as an environment variable, you can also define it like this: `define("WEBPCONVERT_CWEBP_PATH", "/path/to/working/cwebp/for/example/one/in/src/Convert/Converters/Binaries/dir");`

**Comment by rosell-dk** [comment]
@mrbig00: 2.6.0 has been released
