### ISSUE TITLE
Brainstorming WebP capable libraries

### ISSUE THREAD

**Issue by S1SYPHOS** [rosell-dk/webp-convert#33]
- Gmagick (+), but has to be compiled
- Optimus.io (+), PHP example available
- Cairo (?), seems not

**Comment by rosell-dk** [comment]
Gmagick:
It uses the WebP library from Google. So it does the same as cwebp. Same is true with Imagick and Gd, btw. I have googled a little, and found that Gmagick is also available as an extension [https://duntuk.com/how-install-graphicsmagick-gmagick-php-extension]. So it will be available on some systems. So adding gmagick to webp-convert will make conversion possible on more systems. Therefore, it will be a bonus to support gmagick. I'm however not sure how widespread gmagick is.

Optimus:
I know of optimus.io. I also considered that, back when I implemented ewww. It should be easy to implement.. And it would be nice to provide a converter for it, because it may have many users already. Only thing is that we should find out if we are allowed to do it.

Cairo: 
I cannot find anything on webp on their site, so I guess its not supported

**Comment by S1SYPHOS** [comment]
For Optimus.io, see [here](https://github.com/keycdn/php-optimus-api) - since there's no dismissive license and people have to pay for licenses anyway, I guess nobody cares.

**Comment by rosell-dk** [comment]
It seems that new converters are to be the theme of the 1.1.0 release...

**Comment by rosell-dk** [comment]
I think the next converter in production line will be calling the imagick binary directly.

**Comment by rosell-dk** [comment]
How about [Glide](https://github.com/thephpleague/glide) ?
