### ISSUE TITLE
true & false instead of TRUE & FALSE

### ISSUE THREAD

**Issue by daybugging** [rosell-dk/webp-convert#6]
Quick question: does this mean I cannot use lowercase options?
And why would you want to SCREAM booleans? :black_joker:

**Comment by rosell-dk** [comment]
According to the reference, you can use lowercase, camelCase, or WhATEverCASE for booleans (http://php.net/manual/en/language.types.boolean.php). In the reference, they seem to mostly use SCREAM-CASE. But I aggree that it is a bit noisy.

I looked around a bit to discover if there are any conventions. It turns out that the PSR-2 coding standard (https://www.php-fig.org/psr/psr-2/) states that booleans must be lowercase.

For those reasons, changing to lowercase seems a good idea.

Here are some discussion on the topic:
https://stackoverflow.com/questions/2013848/uppercase-booleans-vs-lowercase-in-php
